import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Links } from "../components/Links";

export async function getStaticProps() {
  const res = await fetch("https://api.chucknorris.io/jokes/random");
  const joke = await res.json();

  return {
    props: {
      joke,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 100, // In seconds
  };
}

const Home: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{props.joke.value}</h1>
        <img src="/isr.png" width="70%" alt="" />
      </main>

      <footer className={styles.footer}>
        <Links />
      </footer>
    </div>
  );
};

export default Home;
